name: Rust

on:
  push:
    branches: [master]
    tags: ["v*.*.*"]
#   pull_request:
#     branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --test url --verbose
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "target/release/hum"
          token: ${{ secrets.GITHUB_TOKEN }}
